spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    primary:
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: SYCmysql123!
      url: jdbc:mysql://cdb-b1ppo2ee.bj.tencentcdb.com:10133/syc_trans?useUnicode=true&characterEncoding=utf8
      type: com.alibaba.druid.pool.DruidDataSource
    user:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: SYCmysql123!
      url: jdbc:mysql://cdb-b1ppo2ee.bj.tencentcdb.com:10133/syc_user?useUnicode=true&characterEncoding=utf8
      type: com.alibaba.druid.pool.DruidDataSource
    record:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: SYCmysql123!
      url: jdbc:mysql://cdb-b1ppo2ee.bj.tencentcdb.com:10133/syc_record?useUnicode=true&characterEncoding=utf8
      type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 8088
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true